-- create database 
create database walmart_db;
use walmart_db;

-- data exploration 
select*from walmart_sales;
select count(*) from walmart_sales;

-- NULL values
select * from walmart_sales
where Invoice_ID is null 
or Branch is null 
or City is null 
or Customer_type is null 
or Gender is null 
or Product_line is null 
or Unit_price is null 
or Quantity is null 
or Payment is null 
or cogs is null 
or gross_margin_percentage is null 
or gross_income is null 
or Rating is null ;

-- 1.Total Revenue generated across all Branches

SELECT ROUND(SUM(Total),2) AS Total_Revenue
FROM walmart_sales;

-- 2.Highest Revenue generated Branch

SELECT Branch,
ROUND(SUM(Total),2) AS Revenue
FROM walmart_sales
GROUP BY Branch
ORDER BY Revenue DESC;

-- 3.Product sold the Highest number of units

SELECT Product_line,
SUM(Quantity) AS Units_Sold
FROM walmart_sales
GROUP BY Product_line
ORDER BY Units_Sold DESC;

-- 4.Payment method preferred by Customers

SELECT Payment,
COUNT(*) AS Total_Transactions
FROM walmart_sales
GROUP BY Payment
ORDER BY Total_Transactions DESC;

-- 5.Gender distribution of Customers

SELECT Gender,
COUNT(*) AS Customer_Count
FROM walmart_sales
GROUP BY Gender;

-- 6.Branch having highest customer rating

SELECT Branch,
ROUND(AVG(Rating),2) AS Average_Rating
FROM walmart_sales
GROUP BY Branch
ORDER BY Average_Rating DESC;

-- 7.Top 5 highest-value Transactions

SELECT Invoice_ID,Payment,
ROUND(Total,2) AS Transaction_Value
FROM walmart_sales
ORDER BY Total DESC
LIMIT 5;

-- 8.Highest Revenue generated by customer type

SELECT Customer_type,
ROUND(SUM(Total),2) AS Revenue
FROM walmart_sales
GROUP BY Customer_type
ORDER BY Revenue DESC;

-- 9.Payment method generated the highest Revenue

SELECT Payment,
ROUND(SUM(Total),2) AS Revenue
FROM walmart_sales
GROUP BY Payment
ORDER BY Revenue DESC;

-- 10.Branch sold the Highest quantity of product

SELECT Branch,
SUM(Quantity) AS Total_Units_Sold
FROM walmart_sales
GROUP BY Branch
ORDER BY Total_Units_Sold DESC;